apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fredfossil-com-tls
spec:
  secretName: fredfossil-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fredfossil.com
  dnsNames:
    - fredfossil.com
    - www.fredfossil.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fredfossil.com
          - www.fredfossil.com